# Generated by Django 2.2.1 on 2019-07-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('level', models.CharField(choices=[('e', 'easy'), ('m', 'medium'), ('h', 'hard')], max_length=10)),
                ('topic', models.CharField(choices=[('ll', 'Linked List'), ('q', 'Queue')], max_length=100)),
            ],
        ),
    ]
