# Generated by Django 2.2.1 on 2019-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Threshold', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='sescription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
