# Generated by Django 3.0.5 on 2020-05-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Threshold', '0003_problem_test_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_case',
            field=models.TextField(max_length=100),
        ),
    ]
