# Generated by Django 3.0.5 on 2020-05-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Threshold', '0004_auto_20200506_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='test_case',
            new_name='Input',
        ),
        migrations.AddField(
            model_name='problem',
            name='Output',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
